rust: Fix rust-tree.cc compilation on SPARC
This patch

commit 27a89f84c458ae938bc3eb92ad0d594c06fc3b42
Author: Thomas Schwinge <thomas@codesourcery.com>
Date:   Fri Feb 17 23:36:20 2023 +0100

    '#include "tm_p.h"' in 'gcc/rust/backend/rust-tree.cc'

broke rust bootstrap on SPARC:

In file included from ./tm_p.h:4,
                 from /vol/gcc/src/hg/master/local/gcc/rust/backend/rust-tree.cc:38:
/vol/gcc/src/hg/master/local/gcc/config/sparc/sparc-protos.h:46:47: error: use of enum 'memmodel' without previous declaration
   46 | extern void sparc_emit_membar_for_model (enum memmodel, int, int);
      |                                               ^~~~~~~~

Fixed by including memmodel.h.  Tested on sparc-sun-solaris2.11 and
i386-pc-solaris2.11.

2023-02-20  Rainer Orth  <ro@CeBiTec.Uni-Bielefeld.DE>

	gcc/rust:
	* backend/rust-tree.cc: Include memmodel.h.