[Ada] Fix missing space in error message
On illegal code like:

   type T is new Positive in range 1..5;

the compiler was emitting message:

  error: extra "in"ignored
                  ^^

which lacked a space character.

A tiny diagnostic improvement; spotted while mistakenly typing an
illegal test.

gcc/ada/

	* par-util.adb (Ignore): Add missing space to message string.