testsuite: Only run -fcf-protection test on i?86/x86_64 [PR107213]
This test fails on non-i?86/x86_64 targets because on those targets
we get

  error: '-fcf-protection=full' is not supported for this target

so this patch limits where the test is run.

	PR testsuite/107213

gcc/testsuite/ChangeLog:

	* c-c++-common/pointer-to-fn1.c: Only run on i?86/x86_64.